// Code generated by sqlty. DO NOT EDIT.

package {{.PackageName}}

{{- /*
  Render all necessary structs for all composite types.
*/ -}}

{{- range .Types }}
  {{ if .IsCompositeType }}
    {{ block "struct_declaration" . -}}
      // Template block for struct declaration is missing
    {{- end }}
  {{ end }}
{{ end }}
