// Code generated by sqlty. DO NOT EDIT.

package {{.PackageName}}

import (
	"context"
	"errors"
	"net/http"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

type CtxKey int

// Context keys for keeping useful stuff in the context.
const CtxDBKey = CtxKey(23421)

// Errors returned by generated functions.
var (
	ErrNilArgs               = errors.New("args are nil")
	ErrEmptySpread           = errors.New("spread is empty")
	ErrEmptyStructSpreadList = errors.New("struct spread list is empty")
)

// Txer defines an interface allowing to query database. It's compatible with
// both pgx.Conn and pgxpool.Tx
type Txer interface {
	Exec(context.Context, string, ...any) (pgconn.CommandTag, error)
	Query(context.Context, string, ...any) (pgx.Rows, error)
	QueryRow(context.Context, string, ...any) pgx.Row
}

// Beginner is compatible with pgx.Conn and pgxpool.Pool
type Beginner interface {
	Begin(context.Context) (pgx.Tx, error)
}

// DB groups all generated functions.
type DB struct {
	tx Txer
}

// New creates a new DB.
func New(db Txer) *DB {
	return &DB{tx: db}
}

// Middleware creates a new transaction for every request and attaches it to the context.
// Rolls back after passing it to next.
func Middleware(db Beginner) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			tx, err := db.Begin(ctx)
			if err != nil {
				panic("can't create transaction")
			}
			defer func() { _ = tx.Rollback(ctx) }()

			r = r.WithContext(context.WithValue(ctx, CtxDBKey, tx))
			next.ServeHTTP(w, r)
		})
	}
}

// CtxTx returns a transaction assigned to the context.
func CtxTx(ctx context.Context) (*DB, func(context.Context) error) {
	tx, ok := ctx.Value(CtxDBKey).(pgx.Tx)
	if !ok {
		panic("couldn't get a transaction from context. is middleware configured?")
	}

	return New(tx), tx.Commit
}

// PGErrCode returns the 5-character error code returned by postgresql,
// or an empty string if the error isn't a postgresql error.
func PGErrCode(err error) string {
	if err == nil {
		return ""
	}

	var pgerr *pgconn.PgError
	if errors.As(err, &pgerr) {
		return pgerr.Code
	}

	return ""
}
