// Code generated by sqlty. DO NOT EDIT.

package {{.PackageName}}

{{- range .Enums -}}
{{ $name := .Name }}
type {{ $name }} string

  {{ $values := len .Values }}
  {{ if gt $values 0 }}
    const (
      {{ range .Values }}
        {{- $ident := valueToIdent . -}}
        {{ $name }}_{{ $ident }} {{ $name }} = "{{ . }}"
      {{ end }}
    )
  {{ end}}

var {{ $name }}IdxMap = map[{{ $name }}]int{
  {{ range $idx, $val := .Values }}
    {{- $ident := valueToIdent . -}}
    {{ $name }}_{{ $ident }}: {{ $idx }},
  {{ end }}
}

var {{ $name }}ByIdx = []{{ $name }}{
  {{ range .Values }}
    {{- $ident := valueToIdent . -}}
    {{ $name }}_{{ $ident }},
  {{ end }}
}

{{ end }}
