// Code generated by sqlty. DO NOT EDIT.

package {{.PackageName}}

import (
	"context"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5"
)

{{- if ne .ExecMode "many" }}
// Error: Cursor queries work only in ExecMode "many"
{{- else -}}

{{- /*
  Render all necessary structs (parameters and return values)
  for all provided queries.
*/ -}}

{{- /* Render struct spreads */ -}}
{{- range .Params.StructSpread }}
  {{ if not .IsCompositeType }}
    type {{ .Name }} struct {
      {{- range .Params }}
        {{ .Name }} {{ .Type.Name -}}
      {{ end }}
    }
  {{ end }}
{{ end }}

{{- /* Render return args struct */ -}}
{{ if ne .Params.Name "" }}
  type {{ .Params.Name }} struct {
    {{- range .Params.Scalar }}
      {{ .Name }} {{ .Type.Name -}}
    {{ end }}{{ range .Params.Spread }}
      {{ .Name }} []{{ .Type.Name -}}
    {{ end }}{{ range .Params.StructSpread }}
      {{ .Name }} []*{{ .Name -}}
    {{ end }}
  }
{{ end }}


{{- /* Render return struct */ -}}
{{ $returnsInlineStruct := returnsInlineStruct . }}
{{ if $returnsInlineStruct }}
  {{ block "struct_declaration" .Returns -}}
    // Template block for struct declaration is missing
  {{- end }}
{{ end }}


{{- /* Set helper variables */ -}}

{{- $returnsStruct := returnsStruct . }}
{{- $returnType := printf "*%v" .Returns.Name }}
{{- $returnNilValue := "nil" }}
{{- $returnZeroValue := printf "&%v{}" .Returns.Name }}

{{- if not $returnsStruct -}}
  {{- $returnType = firstParamTypeName .Returns.Params -}}
  {{- $returnNilValue = firstParamNilReturnValue .Returns.Params -}}
  {{- $returnZeroValue = firstParamZeroReturnValue .Returns.Params -}}
{{- end -}}

{{- /* Render cursor structs */ -}}

type {{ .Name }}Cursor struct {
  rows pgx.Rows
}

func (cur *{{ .Name }}Cursor) Next() bool {
	return cur.rows.Next()
}

func (cur *{{ .Name }}Cursor) Close() {
	cur.rows.Close()
}

func (cur *{{ .Name}}Cursor) Err() error {
  return cur.rows.Err()
}

func (cur *{{ .Name }}Cursor) Scan() ({{- $returnType -}}, error) {
  sqltyR := {{ $returnZeroValue }}
  {{ if not $returnsStruct }}
    if err := cur.rows.Scan(&sqltyR); err != nil {
      return {{ $returnNilValue }}, err
    }
  {{ else }}
    if err := cur.rows.Scan(
      {{- range .Returns.Params -}}
        &sqltyR.{{ .Name }},
      {{- end -}}
    ); err != nil {
    return {{ $returnNilValue }}, err
    }
  {{ end }}

  return sqltyR, nil
}

{{- /* Render query function */ -}}

{{ range .Comments }}
  // {{ . -}}
{{ end }}
func (db *DB) {{ .Name }}(ctx context.Context
  {{- if ne .Params.Name "" -}}

    {{- /* If Params.Name is non-empty, render only one argument with its name as type */ -}}
    , args *{{ .Params.Name }}

  {{- else -}}

    {{- /* Otherwise, iterate through basic params... */ -}}
    {{- range .Params.Scalar -}}
      , {{ .Name }} {{ .Type.Name }}
    {{- end -}}

    {{- /* Then render spread args as slices */ -}}
    {{- range .Params.Spread -}}
      , {{ .Name }} []{{ .Type.Name }}
    {{- end -}}

    {{- /* And finally struct spread args */ -}}
    {{- range .Params.StructSpread -}}
      , {{ .Name }} []*{{ .Name }}
    {{- end -}}

  {{- end -}}

  {{- /* End of function params */ -}}
    ) (
  {{- /* Start of return values */ -}}
    *{{ .Name }}Cursor, error) {

  {{- /* Start of function body */ -}}
  {{- " " -}}

  {{ $paramsAsStruct := ne .Params.Name "" -}}

  {{- if hasParams . }}
    {{- if $paramsAsStruct }}
      // Return error when args are missing
      if args == nil {
        return {{ $returnNilValue }}, ErrNilArgs
      }

    {{ end }}
    // Start building a list of arguments which will be passed to Query
    sqltyStmtargs := []any{
      {{ range .Params.Scalar -}}
        {{ if $paramsAsStruct }}args.{{ end }}{{ .Name -}},
      {{ end }}
    }
  {{ end }}

  {{- if needsPrintf . }}
    {{ $spreads := len .Params.Spread -}}
    {{ $structSpreads := len .Params.StructSpread -}}

    sqltyOffset := {{ len .Params.Scalar }} + 1
    sqltySpreads := make([]string, 0, {{ $spreads }} + {{ $structSpreads }})

    {{ if gt $spreads 0 }}
      var sqltySpread []string
      {{ range .Params.Spread }}
        {{- $varname := .Name }}
        {{- if $paramsAsStruct -}}
          {{ $varname = printf "args.%v" .Name -}}
        {{- end }}

        if len({{ $varname }}) == 0 {
          return {{ $returnNilValue }}, ErrEmptySpread
        }

        sqltySpread = make([]string, len({{ $varname }}))
        for sqltyN, sqltyA := range {{ $varname }} {
          sqltySpread[sqltyN] = fmt.Sprintf("$%d", sqltyOffset)
          sqltyStmtargs = append(sqltyStmtargs, sqltyA)
          sqltyOffset++
        }
        sqltySpreads = append(sqltySpreads, strings.Join(sqltySpread, ","))

      {{ end }}
    {{ end }}

    {{ if gt $structSpreads 0 }}
      var sqltyStructSpread []string
      {{ range .Params.StructSpread }}

        {{ $varname := .Name }}
        {{- if $paramsAsStruct -}}
          {{ $varname = printf "args.%v" .Name -}}
        {{- end }}
        {{ $paramsLen := len .Params }}
        if len({{ $varname }}) == 0 {
          return {{ $returnNilValue }}, ErrEmptyStructSpreadList
        }

        for _, sqltySs := range {{ $varname }} {
          sqltySpread := make([]string, {{ $paramsLen }})
          for sqltyN := 0; sqltyN < {{ $paramsLen }}; sqltyN++ {
            sqltySpread[sqltyN] = fmt.Sprintf("$%d", sqltyOffset)
            sqltyOffset++
          }
          sqltyStmtargs = append(sqltyStmtargs,
            {{- range .Params -}}
              sqltySs.{{ .Name }},
            {{- end -}}
          )
          sqltyStructSpread = append(sqltyStructSpread, "(" + strings.Join(sqltySpread, ",") + ")")
        }
        sqltySpreads = append(sqltySpreads, strings.Join(sqltyStructSpread, ","))
        sqltyStructSpread = nil

      {{ end }}
    {{ end }}

    // Convert []string to []any
    sqltyIspreads := make([]any, len(sqltySpreads))
    for sqltyN := range sqltySpreads {
      sqltyIspreads[sqltyN] = sqltySpreads[sqltyN]
    }
    sqltyStmt := fmt.Sprintf(`{{- .Statement -}}`, sqltyIspreads...)

  {{ else }}
    sqltyStmt := `{{- .Statement -}}`
  {{ end }}

  var err error
  sqltyCursor := &{{ .Name }}Cursor{}

  sqltyCursor.rows, err = db.tx.Query(ctx, sqltyStmt{{ if hasParams . }}, sqltyStmtargs...{{ end }})
  if err != nil {
    return nil, err
  }

  return sqltyCursor, err
}

{{- end -}}
