// Code generated by sqlty. DO NOT EDIT.

package {{.PackageName}}

{{- /*
  Render all necessary structs for all composite types.
*/ -}}

{{- range .Types }}
  type {{ .Name }} struct {
    {{ range .Params }}
      {{ .Name }} {{ .Type.Name -}}
    {{ end }}
  }

{{ end }}