// Code generated by sqlty. DO NOT EDIT.

package {{.PackageName}}

{{- range .Enums -}}
{{ $name := .Name }}
type {{ $name }} string

  {{ $values := len .Values }}
  {{ if gt $values 0 }}
    var (
      {{ range .Values }}
        {{- $ident := valueToIdent . -}}
        {{ $name }}_{{ $ident }} {{ $name }} = "{{ . }}"
      {{ end }}
    )
  {{ end}}
{{ end }}