// Code generated by sqlty. DO NOT EDIT.

package {{.PackageName}}

{{- /*
  Returncols is the number of columns returned by the query.
  It's used to determine whether to return a single variable or
  a struct which wraps more columns.
*/ -}}
{{ $returncols := len .Returns -}}

{{- /*
  If there's more than one column to return, a struct is defined.
  When the statement is ran in the exec mode, the function returns
  pgconn.CommandTag. This allows for checking the number of
  rows affected and other things.
*/ -}}
{{- $returnType := printf "*%vRow" .Name }}
{{- $returnNilValue := "nil" }}
{{- $returnZeroValue := printf "&%vRow{}" .Name }}
{{- if eq .ExecMode "exec" }}
  {{- $returnType = "pgconn.CommandTag" }}
  {{- $returnZeroValue := "make(pgconn.CommandTag, 0)" }}
{{- end -}}
{{- if eq $returncols 1 -}}
  {{- $returnType = firstParamTypeName .Returns -}}
  {{ if eq .ExecMode "one" -}}
    {{- $returnNilValue = firstParamNilReturnValue .Returns -}}
  {{- end -}}
  {{- $returnZeroValue = firstParamZeroReturnValue .Returns -}}
{{- end -}}

{{- $paramStructName := printf "%vArgs" .Name }}
{{- $asstruct := .Params.AsStruct }}
{{- $hasParams := hasParams . -}}


{{ if .Params.StructPick.Name -}}
// {{ .Params.StructPick.Name }} allows to pass many values to {{ .Name }}.
type {{ .Params.StructPick.Name }} struct {
{{- range .Params.StructPick.Params }}
  {{ .Name }} {{ .Type.Name -}}
{{ end }}
}{{ end }}

{{ if .Params.AsStruct }}
// {{ .Name -}}Args is an argument set passed to {{ .Name }}
type {{ $paramStructName }} struct {
{{- range .Params.Basic }}
  {{ .Name }} {{ .Type.Name -}}
{{ end }}{{ range .Params.Spread }}
  {{ .Name }} []{{ .Type.Name -}}
{{ end }}
{{ if .Params.StructPick.Name -}}
  {{ .Params.StructPick.Name }} []*{{ .Params.StructPick.Name }}
{{end}}
}{{ end }}

{{ if gt $returncols 1 }}
// {{ .Name -}}Row is a result row returned by {{ .Name }}
type {{ .Name }}Row struct {
{{- range .Returns }}
  {{ .Name }} {{ .Type.Name -}}
{{ end }}
}{{ end }}

{{ range .Comments }}
// {{ . -}}
{{ end }}
func (db *DB) {{.Name}}(ctx context.Context
  {{- if .Params.AsStruct -}}
    {{- /* If AsStruct is true, render only one argument with the {.Name}Args type */ -}}
    , args *{{ .Name }}Args
  {{- else -}}
    {{- /* Otherwise, iterate through basic params... */ -}}
    {{- range .Params.Basic -}}
      , {{ .Name }} {{ .Type.Name }}
    {{- end -}}
    {{- /* Then render spread args as slices */ -}}
    {{- range .Params.Spread -}}
      , {{ .Name }} []{{ .Type.Name }}
    {{- end -}}
    {{- /* And if StructPick exists, append it as well */ -}}
    {{- if .Params.StructPick.Name -}}
      , {{ .Params.StructPick.Name }} []*{{ .Params.StructPick.Name }}
    {{- end -}}
  {{- end -}}
  {{- /* End of function params */ -}}
    ) (

  {{- /* Start of return values */ -}}

  {{- if eq .ExecMode "many" -}}
    []
  {{- end -}}
  {{- $returnType -}}, error) {

  {{- /* Start of function body */ -}}

  {{- " " }}
  {{- if $hasParams }}
    {{- if $asstruct }}
      if args == nil {
        return {{ $returnNilValue }}, ErrNilArgs
      }

    {{ end -}}

    sqltyStmtargs := []interface{}{
      {{ range .Params.Basic -}}
        {{ if $asstruct }}args.{{ end }}{{ .Name -}},
      {{ end }}
    }
  {{ end }}

  {{- if needsPrintf . }}
    {{ $spreads := len .Params.Spread -}}
    sqltyOffset := {{ len .Params.Basic }} + 1
    sqltySpreads := make([]string, 0, {{ $spreads }}
      {{- if ne .Params.StructPick.Name "" }}+1{{ end }})

    {{ if gt $spreads 0 }}
      var sqltySpread []string
      {{ range .Params.Spread }}
        {{- $varname := .Name }}
        {{- if $asstruct -}}
          {{ $varname = printf "args.%v" .Name -}}
        {{- end }}

        if len({{ $varname }}) == 0 {
          return {{ $returnNilValue }}, ErrEmptySpread
        }

        sqltySpread = make([]string, len({{ $varname }}))
        for sqltyN, sqltyA := range {{ $varname }} {
          sqltySpread[sqltyN] = fmt.Sprintf("$%d", sqltyOffset)
          sqltyStmtargs = append(sqltyStmtargs, sqltyA)
          sqltyOffset++
        }
        sqltySpreads = append(sqltySpreads, "(" + strings.Join(sqltySpread, ",") + ")")

      {{ end }}
    {{ end }}

    {{ if ne .Params.StructPick.Name "" }}
      {{- $varname := .Params.StructPick.Name }}
      {{- if $asstruct -}}
        {{ $varname = printf "args.%v" .Params.StructPick.Name -}}
      {{- end }}
      {{- $paramsLen := len .Params.StructPick.Params }}
      if len({{ $varname }}) == 0 {
        return {{ $returnNilValue }}, ErrEmptyStructPickList
      }

      for _, sqltySp := range {{ $varname }} {
        sqltySpread := make([]string, {{ $paramsLen }})
        for sqltyN := 0; sqltyN < {{ $paramsLen }}; sqltyN++ {
          sqltySpread[sqltyN] = fmt.Sprintf("$%d", sqltyOffset)
          sqltyStmtargs = append(sqltyStmtargs,
            {{- range .Params.StructPick.Params -}}
              sqltySp.{{ .Name }},
            {{- end -}}
          )
          sqltyOffset++
        }
        sqltySpreads = append(sqltySpreads, sqltySpread...)
      }
    {{ end }}
    // Convert []string to []interface
    sqltyIspreads := make([]interface{}, len(sqltySpreads))
    for sqltyN := range sqltySpreads {
      sqltyIspreads[sqltyN] = sqltySpreads[sqltyN]
    }
    sqltyStmt := fmt.Sprintf(`{{- .Statement -}}`, sqltyIspreads...)
  {{ else }}
    sqltyStmt := `{{- .Statement -}}`
  {{ end }}

  {{ if eq .ExecMode "many" }}
  sqltyRows, err := db.tx.Query(ctx, sqltyStmt{{ if $hasParams }}, sqltyStmtargs...{{ end }})
  if err != nil {
    return {{ $returnNilValue }}, err
  }
  defer sqltyRows.Close()

  var sqltyResults []{{ $returnType }}
  for sqltyRows.Next() {
    sqltyR := {{ $returnZeroValue }}
    {{ if eq $returncols 1 }}
      if err := sqltyRows.Scan(&sqltyR); err != nil {
        return {{ $returnNilValue }}, err
      }
    {{ else }}
      if err := sqltyRows.Scan(
        {{- range .Returns -}}
          &sqltyR.{{ .Name }},
        {{- end -}}
      ); err != nil {
      return {{ $returnNilValue }}, err
      }
    {{ end }}
    sqltyResults = append(sqltyResults, sqltyR)
  }

  return sqltyResults, sqltyRows.Err()
  {{ else if eq .ExecMode "one" }}
    {{- if eq $returncols 1 -}}
      sqltyResult := {{ $returnZeroValue }}
      err := db.tx.QueryRow(ctx, sqltyStmt{{ if $hasParams }}, sqltyStmtargs...{{ end }}).Scan(&sqltyResult)
    {{ else -}}
      sqltyResult := &{{ .Name }}Row{}
      err := db.tx.QueryRow(ctx, sqltyStmt{{ if $hasParams }}, sqltyStmtargs...{{ end }}).Scan(
        {{- range .Returns -}}
          &sqltyResult.{{ .Name }},
        {{- end -}}
      )
    {{ end -}}
    if err != nil {
      return {{ $returnNilValue }}, err
    }

    return sqltyResult, nil
  {{ else }} {{- /* exec mode */ -}}
    return db.tx.Exec(ctx, sqltyStmt{{ if $hasParams }}, sqltyStmtargs...{{ end }})
  {{- end -}}
}